server:
  port: 9002

spring:
  appication:
    name: MOVIE-SERVICE

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-regítry:
      value: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
