server:
  port: 9001

spring:
  application:
    name: DIRECTOR-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://lit-reef-49057.herokuapp.com/

  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 30000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttempts: 3
        waitDuration: 2s

  ratelimiter:
    instances:
      basicExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 1s



#    management:
#      endpoints:
#        web:
#          exposure:
#            include: '*'


